--TABLA DOCUMENTOS
CREATE TABLE TBL_DOCUMENTO(
    nIdDocumento INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombreDoc VARCHAR(100),
)
GO

--TABLA ROLES
CREATE TABLE TBL_ROL(
    nIdRol INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombreRol VARCHAR(100)    
)
GO

--TABLA USUARIOS
CREATE TABLE TBL_USUARIO(
    nIdUsuario INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombres VARCHAR(MAX),
	  sApellidos VARCHAR(MAX),
	  nTipoDoc INT,
    FOREIGN KEY (nTipoDoc) REFERENCES TBL_DOCUMENTO(nIdDocumento),
    sNumDoc VARCHAR(15),
	  sSexo VARCHAR(1),  
	  sDireccion VARCHAR(MAX),
	  nTelefono INT,
	  dFechaNacimiento DATE,
	  bEstado BIT NOT NULL DEFAULT 1
)
GO

--TABLA LOGIN
CREATE TABLE TBL_LOGIN(
    nIdUsuario INT NOT NULL,
	FOREIGN KEY (nIdUsuario) REFERENCES TBL_USUARIO(nIdUsuario),
    sNombreUsuario VARCHAR(100),
    sContrasenia VARCHAR(MAX)
)
GO


--TABLA PRODUCTOS
CREATE TABLE TBL_PRODUCTO(
    nIdProducto INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
    sNombre VARCHAR(MAX),
    sDescripcion VARCHAR(MAX),	      
	nStock INT,	
	bEstado BIT NOT NULL DEFAULT 1
)
GO

--TABLA HISTORIAL
CREATE TABLE TBL_HISTORIAL(
    nIdHistorial INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nIdUsuario INT,
	FOREIGN KEY (nIdUsuario) REFERENCES TBL_USUARIO(nIdUsuario),
	nIdProducto INT,
	FOREIGN KEY (nIdProducto) REFERENCES TBL_PRODUCTO(nIdProducto),
    sAccion VARCHAR(100),
    dFecha DATETIME
)
GO